### ISSUE TITLE
Potential rename to vignetteapp/wiki?

### ISSUE THREAD

**Issue by iojcde** [vignetteapp/docs#22]
This repo is deployed at https://wiki.vignetteap.org .

I think the subdomain should match the repo name, what does everyone else think?

**Comment by iojcde** [comment]
Or we could change the subdomain to https://docs.vignetteapp.or , but wiki.vignetteapp.org looks better imo

**Comment by iojcde** [comment]
@sr229 Any thoughts?

**Comment by sr229** [comment]
I don't think I need my comments here. I already did it xd
